### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by 1005183361** [vahdat-ab/OODL#1]
Hello, when I run download_required_files.ipynb, I found that the two file_id download links have expired, can you provide new data? My email is 1005183361@qq.com, thanks!

**Comment by vahdat-ab** [comment]
Hi @1005183361 
It is a download issue and the links are valid. You can use the following direct links to download them. I'll investigate why this happens.
https://drive.google.com/file/d/1YSsgVKA2KuLh8CpGGmtmZihaLHDsS6y9/view?usp=share_link
https://drive.google.com/file/d/1C-MSNyaEgwQIeqkHhygoHcTkO4RAA9Wm/view?usp=share_link

**Comment by vahdat-ab** [comment]
The code was fixed by using another library (`gdown`) for downloading from Google driver.

**Comment by vahdat-ab** [comment]
fixed!

**Comment by 1005183361** [comment]
> `gdown`通过使用另一个库 ( ) 从 Google 驱动程序下载来修复代码。



> 你好@1005183361 这是一个下载问题，链接有效。您可以使用以下直接链接下载它们。我会调查为什么会这样。 [https://drive.google.com/file/d/1YSsgVKA2KuLh8CpGGmtmZihaLHDsS6y9/view?usp=share_link ](https://drive.google.com/file/d/1YSsgVKA2KuLh8CpGGmtmZihaLHDsS6y9/view?usp=share_link) https://drive.google.com/file/d/1C-MSNyaEgwQIeqkHhygoHcTkO4RAA9Wm/view?usp=share_link

Thank you so much
